### ISSUE TITLE
No attribute validation_file in train.py?

### ISSUE THREAD

**Issue by SumNeuron** [princeton-nlp/SimCSE#116]
```python
os.system(f'bash ./data/download_nli.sh')
os.system(
    'cd SimCSE;'
    'python train.py '
    '--model_name_or_path bert-base-uncased'
    '--train_file data/nli_for_simcse.csv '
    '--output_dir result/my-sup-simcse-bert-base-uncased '   
    '--num_train_epochs 3 '
    '--per_device_train_batch_size 128 '
    '--learning_rate 5e-5 '
    '--max_seq_length 32 '
    '--evaluation_strategy steps '
    '--metric_for_best_model stsb_spearman '
    '--load_best_model_at_end '
    '--eval_steps 125 '
    '--pooler_type cls '
    '--overwrite_output_dir '
    '--temp 0.05 '
    '--do_train '
    '--do_eval '
    '--fp16 '
    '"$@"'
)
```

```
Traceback (most recent call last):
  File "/Users/sumner/Downloads/Replication/SimCSE/train.py", line 584, in <module>
    main()
  File "/Users/sumner/Downloads/Replication/SimCSE/train.py", line 257, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/Users/sumner/miniforge3/lib/python3.9/site-packages/transformers/hf_argparser.py", line 157, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 12, in __init__
  File "/Users/sumner/Downloads/Replication/SimCSE/train.py", line 179, in __post_init__
    if self.dataset_name is None and self.train_file is None and self.validation_file is None:
AttributeError: 'DataTrainingArguments' object has no attribute 'validation_file'
```

**Comment by gaotianyu1350** [comment]
Can you try directly using a script to run instead of inside python?

**Comment by SumNeuron** [comment]
Yes. Same error.

**Comment by KawaiiNotHawaii** [comment]
Any solution to this issue? I am having the same error.

**Comment by XiaochaiQAQ** [comment]
I got same error as well.

**Comment by ashutoshsaboo** [comment]
Same error even when I tried today. @gaotianyu1350 was this fixed? Or is there a solution to the same?
