### ISSUE TITLE
subprocess.CalledProcessError

### ISSUE THREAD

**Issue by fspanda** [princeton-nlp/SimCSE#151]
Hi
I tried to run the "run_sup_example.sh", but I got the following error.

You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "train.py", line 585, in <module>
    main()
  File "train.py", line 399, in main
    raise NotImplementedError
NotImplementedError
Traceback (most recent call last):
  File "/opt/conda/envs/sim_cse/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/sim_cse/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/sim_cse/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/opt/conda/envs/sim_cse/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/envs/sim_cse/bin/python', '-u', 'train.py', '--local_rank=0', '--model_name_or_path', 'bert-large-uncased', '--train_file', 'data/train_sample.csv', '--output_dir', 'result/my-sup-simcse-bert-large-uncased', '--num_train_epochs', '3', '--per_device_train_batch_size', '512', '--learning_rate', '1e-5', '--max_seq_length', '64', '--evaluation_strategy', 'steps', '--metric_for_best_model', 'stsb_spearman', '--load_best_model_at_end', '--eval_steps', '125', '--pooler_type', 'cls', '--overwrite_output_dir', '--temp', '0.05', '--do_train', '--do_eval', '--fp16']' returned non-zero exit status 1.

I saw a similar issue and used the solution from there. I used a single gpu, and deleted the temporary files.
But still, the same error occurs.

My environment is pytorch version 1.7.1 as you recommended, and I installed it according to your requirements.txt file.

Please let me know if there is a way to solve it.

**Comment by dustn1259** [comment]
I have the same error just as you! If you solve this problem, share with me.
