### ISSUE TITLE
Error while loading the dataset

### ISSUE THREAD

**Issue by leoozy** [princeton-nlp/SimCSE#22]
Hello, thanks for releasing the code. I encountered an error while loading the dataset.  I run the dowload_wili.sh firstly and then bash ./run_unsup_example.sh  
` 
if data_args.train_file is not None:
        data_files["train"] = data_args.train_file
    extension = data_args.train_file.split(".")[-1]
    if extension == "txt":
        extension = "text"
    if extension == "csv":
        datasets = load_dataset(extension, data_files=data_files, cache_dir='./data/', delimiter="\t" if "tsv" in data_args.train_file else ",")
    else:
        datasets = load_dataset(extension, data_files=data_files, cache_dir='./data/')`

the error is :
Traceback (most recent call last):
  File "train.py", line 582, in <module>
    main()
  File "train.py", line 308, in main
    datasets = load_dataset(extension, data_files=data_files, cache_dir=DATA_DIR)
  File "/home/sysadmin/anaconda3/envs/zjl/lib/python3.6/site-packages/datasets/load.py", line 591, in load_dataset
    path, script_version=script_version, download_config=download_config, download_mode=download_mode, dataset=True
  File "/home/sysadmin/anaconda3/envs/zjl/lib/python3.6/site-packages/datasets/load.py", line 267, in prepare_module
    local_path = cached_path(file_path, download_config=download_config)
  File "/home/sysadmin/anaconda3/envs/zjl/lib/python3.6/site-packages/datasets/utils/file_utils.py", line 343, in cached_path
    max_retries=download_config.max_retries,
  File "/home/sysadmin/anaconda3/envs/zjl/lib/python3.6/site-packages/datasets/utils/file_utils.py", line 617, in get_from_cache
    raise ConnectionError("Couldn't reach {}".format(url))
ConnectionError: Couldn't reach https://raw.githubusercontent.com/huggingface/datasets/1.2.1/datasets/text/text.py

**Comment by leoozy** [comment]
solved after changing a network
