### ISSUE TITLE
Key Error bug when run evaluation example code from README.md

### ISSUE THREAD

**Issue by JiazhaoLi** [princeton-nlp/SimCSE#43]

**Comment by JiazhaoLi** [comment]
Hi 

I have some unexpected bug when run evluation example code :
`python evaluation.py --model_name_or_path princeton-nlp/unsup-simcse-bert-base-uncased --pooler cls_before_pooler --task_set sts --mode test `

------ test ------
Traceback (most recent call last):
  File "evaluation.py", line 206, in <module>
    main()
  File "evaluation.py", line 183, in main
    scores.append("%.2f" % (results[task]['all']['spearman']['all'] * 100))
KeyError: 'all'
