### ISSUE TITLE
error when training run_unsup_example.sh

### ISSUE THREAD

**Issue by mode007** [princeton-nlp/SimCSE#58]
When i run run_unsup_example.sh, an error happend:
6%|████████▎                                                                                                                        | 125/1954 [01:30<17:25,  1.75it/s]Traceback (most recent call last):
  File "train.py", line 584, in <module>
    main()
  File "train.py", line 548, in main
    train_result = trainer.train(model_path=model_path)
  File "/home/yutianyao/whoiswho/train_simcse/simcse/trainers.py", line 507, in train
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch)
  File "/root/anaconda3/envs/myven/lib/python3.7/site-packages/transformers/trainer.py", line 1004, in _maybe_log_save_evaluate
    metrics = self.evaluate()
  File "/home/yutianyao/whoiswho/train_simcse/simcse/trainers.py", line 129, in evaluate
    results = se.eval(tasks)
  File "./SentEval/senteval/engine.py", line 59, in eval
    self.results = {x: self.eval(x) for x in name}
  File "./SentEval/senteval/engine.py", line 59, in <dictcomp>
    self.results = {x: self.eval(x) for x in name}
  File "./SentEval/senteval/engine.py", line 85, in eval
    self.evaluation = STSBenchmarkEval(tpath + '/downstream/STS/STSBenchmark', seed=self.params.seed)
  File "./SentEval/senteval/sts.py", line 165, in __init__
    train = self.loadFile(os.path.join(task_path, 'sts-train.csv'))
  File "./SentEval/senteval/sts.py", line 173, in loadFile
    with io.open(fpath, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './SentEval/data/downstream/STS/STSBenchmark/sts-train.csv'

Could you please tell me why?  thank you!

**Comment by mode007** [comment]
I solved it! sorry, because i I didn't download eval/data
