### ISSUE TITLE
ImportError: cannot import name '_model_unwrap' from 'transformers.trainer' 

### ISSUE THREAD

**Issue by FanWan** [princeton-nlp/SimCSE#60]
when I was trying to start the train script, the error above occured.

transformers version:  4.8.2
torch version: 1.7.1 
cuda: 10.1

**Comment by gaotianyu1350** [comment]
Could you try `transformers==4.2.1`?

**Comment by FanWan** [comment]
> Could you try `transformers==4.2.1`?
ok , i will try.

**Comment by FanWan** [comment]
hello, after running  run_unsup_example.sh, the following error occured.


{'eval_stsb_spearman': 0.7886007808766199, 'eval_sickr_spearman': 0.7334500487569333, 'eval_avg_sts': 0.7610254148167765, 'epoch': 0.99}
Traceback (most recent call last):
  File "train.py", line 584, in <module>
    main()
  File "train.py", line 548, in main
    train_result = trainer.train(model_path=model_path)
  File "/mnt/work/wanfan01/repo/SimCSE-main/simcse/trainers.py", line 464, in train
    tr_loss += self.training_step(model, inputs)
  File "/mnt/work/anaconda3/envs/wanfan01_py3/lib/python3.8/site-packages/transformers/trainer.py", line 1248, in training_step
    loss = self.compute_loss(model, inputs)
  File "/mnt/work/anaconda3/envs/wanfan01_py3/lib/python3.8/site-packages/transformers/trainer.py", line 1277, in compute_loss
    outputs = model(**inputs)
  File "/mnt/work/anaconda3/envs/wanfan01_py3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/work/anaconda3/envs/wanfan01_py3/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 162, in forward
    return self.gather(outputs, self.output_device)
  File "/mnt/work/anaconda3/envs/wanfan01_py3/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 174, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/mnt/work/anaconda3/envs/wanfan01_py3/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    res = gather_map(outputs)
  File "/mnt/work/anaconda3/envs/wanfan01_py3/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 61, in gather_map
    return type(out)(((k, gather_map([d[k] for d in outputs]))
  File "<string>", line 6, in __init__
  File "/mnt/work/anaconda3/envs/wanfan01_py3/lib/python3.8/site-packages/transformers/file_utils.py", line 1383, in __post_init__
    for element in iterator:
  File "/mnt/work/anaconda3/envs/wanfan01_py3/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 61, in <genexpr>
    return type(out)(((k, gather_map([d[k] for d in outputs]))
  File "/mnt/work/anaconda3/envs/wanfan01_py3/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 55, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/mnt/work/anaconda3/envs/wanfan01_py3/lib/python3.8/site-packages/torch/nn/parallel/_functions.py", line 71, in forward
    return comm.gather(inputs, ctx.dim, ctx.target_device)
  File "/mnt/work/anaconda3/envs/wanfan01_py3/lib/python3.8/site-packages/torch/nn/parallel/comm.py", line 230, in gather
    return torch._C._gather(tensors, dim, destination)
RuntimeError: Input tensor at index 3 has invalid shape [14, 14], but expected [14, 17]
^M100%|█████████▉| 3906/3907 [26:36<00:00,  2.45it/s]

**Comment by gaotianyu1350** [comment]
Did you use the single-GPU script while the job took several GPUs? In this case, either change the script to our multip-GPU script or make sure you only use one GPU (by setting `CUDA_VISIBLE_DEVICES`).

**Comment by FanWan** [comment]
> Did you use the single-GPU script while the job took several GPUs? In this case, either change the script to our multip-GPU script or make sure you only use one GPU (by setting `CUDA_VISIBLE_DEVICES`).

Got it, thank you so much. I did use the single-GPU script while the job took several GPUs.

**Comment by dragonStyle1985** [comment]
from transformers.trainer import unwrap_model in transformer 4.9.1.

**Comment by wacharlin** [comment]
Hi，
 I have a question that as you shown that, _In run_unsup_example.sh, we provide a single-GPU (or CPU) example for the unsupervised version,_but when i run `run_unsup_example.sh`, I found that i was using multiple GPUs and then met the same error that shape of tensor not matched. could you please teach me why does this happen? isn't it using only one GPU? 
thank you!

**Comment by wacharlin** [comment]
Hi @[gaotianyu1350](https://github.com/gaotianyu1350)，
I have a question that as you shown that, 

> In run_unsup_example.sh, we provide a single-GPU (or CPU) example for the unsupervised version

 ,but when i run run_unsup_example.sh, I found that i was using multiple GPUs and then met the same error that shape of tensor not matched. could you please teach me why does this happen? isn't it using only one GPU?
thank you!

**Comment by gaotianyu1350** [comment]
You need to designate to use only one GPU by setting `export CUDA_VISIBLE_DEVICES={GPU ID}`.

**Comment by ashutoshsaboo** [comment]
> from transformers.trainer import unwrap_model in transformer 4.9.2.

Thanks @dragonStyle1985 for this!! The old transformers version that this lib supports had some bugs (more specifically this one: https://github.com/huggingface/transformers/issues/12762 ), which warranted for a force transformers version upgrade, once i changed the import here it re-ran successfully!
